# Generated by Django 4.2.5 on 2023-09-27 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
