# Generated by Django 4.2.5 on 2023-09-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ForeignKey(choices=[('Apparel and Clothing', 'Apparel and Clothing'), ('Toys and Games', 'Toys and Games'), ('Electronics and Gadgets', 'Electronics and Gadgets'), ('Home and Living', 'Home and Living'), ('Sports and Outdoor', 'Sports and Outdoor'), ('Beauty and Personal Care', 'Beauty and Personal Care'), ('Books and Media', 'Books and Media'), ('Food and Grocery', 'Food and Grocery'), ('Automotive and Parts', 'Automotive and Parts'), ('Health and Wellness', 'Health and Wellness')], on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
