# Generated by Django 4.2.5 on 2023-09-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_category_options_alter_listing_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('Apparel and Clothing', 'Clothing'), ('Toys and Games', 'Toys'), ('Electronics and Gadgets', 'Electronics'), ('Home and Living', 'Home'), ('Sports and Outdoor', 'Sports'), ('Beauty and Personal Care', 'Beauty'), ('Books and Media', 'Books'), ('Food and Grocery', 'Food'), ('Automotive and Parts', 'Automotive'), ('Health and Wellness', 'Health')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ForeignKey(choices=[('Apparel and Clothing', 'Clothing'), ('Toys and Games', 'Toys'), ('Electronics and Gadgets', 'Electronics'), ('Home and Living', 'Home'), ('Sports and Outdoor', 'Sports'), ('Beauty and Personal Care', 'Beauty'), ('Books and Media', 'Books'), ('Food and Grocery', 'Food'), ('Automotive and Parts', 'Automotive'), ('Health and Wellness', 'Health')], on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
