# Generated by Django 4.2.5 on 2023-09-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_category_categories_alter_listing_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.CharField(choices=[('Apparel and Clothing', 'Clothing'), ('Toys and Games', 'Toys'), ('Electronics and Gadgets', 'Electronics'), ('Home and Living', 'Home'), ('Sports and Outdoor', 'Sports'), ('Beauty and Personal Care', 'Beauty'), ('Books and Media', 'Books'), ('Food and Grocery', 'Food'), ('Automotive and Parts', 'Automotive'), ('Health and Wellness', 'Health')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
