# Generated by Django 4.2.5 on 2023-10-13 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bid_options_remove_user_watchlist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'verbose_name': 'Watchlist'},
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
